# OpenAI API Configuration
openai:
  # Replace with your OpenAI API key
  api-key: "your-api-key-here"

# Plugin Settings
settings:
  # Maximum response length in characters
  max-response-length: 1000
  # Cooldown between messages in seconds
  cooldown: 5
