name: MCP
version: 1.0.0
main: com.example.mcp.MCPPlugin
api-version: "1.20"
description: A Minecraft plugin that integrates with OpenAI
author: YourName
commands:
  mcp:
    description: Chat with AI
    usage: /<command> <prompt>
    permission: mcp.chat
