# OpenAI API Configuration
openai:
  # Replace this with your OpenAI API key
  api-key: "your-api-key-here"
  # AI model to use
  model: "text-davinci-003"
  # Maximum tokens in AI response
  max-tokens: 100
  # Temperature (0.0 to 1.0) - higher values make responses more random
  temperature: 0.7

# Plugin Settings
settings:
  # Maximum tokens in AI response
  max-tokens: 100
  # Temperature (0.0 to 1.0) - higher values make responses more random
  temperature: 0.7
  # AI model to use
  model: "text-davinci-003"
